name: razor-blog
services:
    razor-blog-app:
        container_name: razor-blog-app
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        environment:
            - ASPNETCORE_URLS=https://+:5000;https://+:5001
            - ASPNETCORE_HTTPS_PORT=5000,5001

            - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}

            - SeedUser__Password=${SeedUser__Password}
            - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}

            # AWS Credentials
            - Aws__SecretKey=${Aws__SecretKey}
            - Aws__S3__BucketName=${Aws__S3__BucketName}
            - Aws__AccessKey=${Aws__AccessKey}
        depends_on:
            - razorblogdb
        volumes:
            - ~/.aspnet/https:/https:ro
    razorblogdb:
        container_name: razorblogdb
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: ${SqlServer__Password}
            ACCEPT_EULA: Y
            MSSQL_PID: Express
