name:  simple-forum
services:
    simple-forum-app:
        container_name: simple-forum-app
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        command: bash -c 'while ! </dev/tcp/simpleforumdb/1433; do echo "Waiting for database"; sleep 3; done; export AWS_PROFILE=simple-forum; dotnet SimpleForum.Web.dll'
        environment:
            - ASPNETCORE_URLS=http://+:5000;http://+:5001
            - SeedUser__Password=${SeedUser__Password}
            - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
        depends_on:
            - simpleforumdb
        volumes:
            - ~/.aws:/root/.aws:ro
    simpleforumdb:
        container_name: simpleforumdb
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: ${SqlServer__Password}
            ACCEPT_EULA: Y
            MSSQL_PID: Express
