name: razor-blog
services:
    razor-blog-app:
        container_name: razor-blog-app
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        command: bash -c 'while ! </dev/tcp/razorblogdb/1433; do echo "Waiting for database"; sleep 3; done; dotnet RazorBlog.Web.dll'
        environment:
            - ASPNETCORE_URLS=http://+:5000;http://+:5001
            - SeedUser__Password=${SeedUser__Password}
            - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
        depends_on:
            - razorblogdb
        volumes:
            - ~/.aws:/root/.aws:ro
    razorblogdb:
        container_name: razorblogdb
        ports:
            - "1433:1433"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: ${SqlServer__Password}
            ACCEPT_EULA: Y
            MSSQL_PID: Express
